export { default as About } from './About';
export { default as ActivationResult } from './ActivationResult';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Premium } from './Premium';
export { default as Purchase } from './Purchase';
export { default as Register } from './Register';
export { default as ReportArtist } from './ReportArtist';
export { default as ResetPassword } from './ResetPassword';
